blog/urls.py
from django.urls import path

from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.PostList.as_view(template_name="blog/index.html"), name='index'),
    path('portfolio/', views.portfolio_detail, name='portfolio'),
    path('history/', views.PostList.as_view(template_name="blog/history.html"), name='history'),
    path('post/<slug:slug>/', views.PostDetail.as_view(), name='detail'),
    path('about/', views.about_detail, name='about'),
    path('tag/<slug:slug>/', views.TagIndexView.as_view(), name='tagged'),
    path('category/<slug:slug>/', views.CategoryIndexView.as_view(), name='category'),
]

mysite/urls.py
import os
from django.contrib import admin
from django.urls import include, path
from decouple import config

if 'AWS_ADMIN' in os.environ:
    ADMIN = os.environ.get('AWS_ADMIN')
else:
    ADMIN = config('ADMIN')
urlpatterns = [
    path('', include('blog.urls')),
    path(ADMIN, admin.site.urls),
    path('martor/', include('martor.urls')),
]

blog/models.py
from django.db import models
from django.urls import reverse
from taggit.managers import TaggableManager
from django.utils import timezone
from django.template.defaultfilters import slugify
from django.core.exceptions import ValidationError


# Model that describes a category


class Category(models.Model):
    category_name = models.CharField(max_length=32)
    slug = models.SlugField(unique=True, max_length=100)

    class Meta:
        verbose_name = "Category"
        verbose_name_plural = "Categories"

    def __unicode__(self):
        return self.category_name

    def __str__(self):
        return self.category_name

    def get_absolute_url(self):
        return reverse('blog:category', kwargs={"slug": self.slug})

    # Prevents new Categories from having the same name as existing categories.
    # This ensures unique slug url for categories
    def clean(self):
        temp = slugify(self.category_name)
        if Category.objects.filter(slug=temp).exists():
            category = Category.objects.get(slug=temp)
            if self.id is not category.id:
                name = slugify(category.category_name)
                if temp == name:
                    raise ValidationError('This category already exists.')

    # Entering categories is case insensitive for slug url, so 'General' is same as 'general'
    # This method only activates when your model updates go through save.
    # If you write code that does an .update() on a queryset, you will skip the slugify step
    def save(self, *args, **kwargs):
        self.slug = slugify(self.category_name)
        super(Category, self).save(*args, **kwargs)

# Model that describes a blog post


class Post(models.Model):
    post_author = models.ForeignKey('auth.User', on_delete=models.SET_NULL, null=True)
    post_text = models.TextField()
    pub_date = models.DateTimeField(default=timezone.now)
    post_title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True, max_length=200)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True)
    tags = TaggableManager(blank=True)

    def __unicode__(self):
        return self.post_title

    def __str__(self):
        return self.post_title

    def get_absolute_url(self):
        return reverse('blog:detail', kwargs={"slug": self.slug})

    def clean(self):
        temp = slugify(self.post_title)
        if Post.objects.filter(slug=temp).exists():
            post = Post.objects.get(slug=temp)
            if self.id is not post.id:
                title = slugify(post.post_title)
                if temp == title:
                    raise ValidationError('This post already exists.')

    def save(self, *args, **kwargs):
        self.slug = slugify(self.post_title)
        super(Post, self).save(*args, **kwargs)

blog/views.py
from django.shortcuts import render
from django.views import generic
from .models import Post, Category
from taggit.models import Tag
from django.utils import timezone


# Generates context name for categories
class CategoryMixin(object):
    def get_context_data(self, **kwargs):
        context = super(CategoryMixin, self).get_context_data(**kwargs)
        context['category'] = Category.objects.all()
        return context


# Displays a list of posts by their categories
class CategoryIndexView(CategoryMixin, generic.ListView):
    template_name = "blog/history.html"
    model = Post
    paginate_by = 4
    context_object_name = 'latest_post_list'

    # Filters posts by category slug url and orders them by publication date
    def get_queryset(self):
        return Post.objects.filter(
            category__slug=self.kwargs.get('slug'),
            pub_date__lte=timezone.now()
        ).order_by('-pub_date')


# Generates context name for tags
class TagMixin(object):
    def get_context_data(self, **kwargs):
        context = super(TagMixin, self).get_context_data(**kwargs)
        context['tags'] = Tag.objects.all()
        return context


# Displays a list of posts by their tags
class TagIndexView(CategoryMixin, TagMixin, generic.ListView):
    template_name = "blog/history.html"
    model = Post
    paginate_by = 4
    context_object_name = 'latest_post_list'

    # Filters posts by tag slug url and orders them by publication date
    def get_queryset(self):
        return Post.objects.filter(
            tags__slug=self.kwargs.get('slug'),
            pub_date__lte=timezone.now()
        ).order_by('-pub_date')


# Displays a list of post
class PostList(CategoryMixin, TagMixin, generic.ListView):
    model = Post
    context_object_name = 'latest_post_list'
    paginate_by = 4

    # Return the last published posts (not including posts published in the future).
    def get_queryset(self):
        return Post.objects.filter(
            pub_date__lte=timezone.now()
        ).order_by('-pub_date')


# Displays the content inside a post
class PostDetail(generic.DetailView):
    model = Post
    template_name = 'blog/detail.html'

    #  Excludes any posts that aren't published yet.
    def get_queryset(self):
        return Post.objects.filter(pub_date__lte=timezone.now())


# Displays the about page using the raw html file
def about_detail(request):
    return render(request, 'blog/about.html')


# Displays the portfolio page using the raw html file
def portfolio_detail(request):
    return render(request, 'blog/portfolio.html')

blog/templates/blog/about.html
{% extends 'blog/base.html' %}
{% block content %} 
{% load static %} 
<!-- Page Header -->
<header class="masthead" style="background-image: url('{% static 'blog/img/background.jpg' %}')">
  <div class="overlay"></div>
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        <div class="site-heading">
          <h1>
            <a class="custom-background-title" href="{% url 'blog:about' %}">About Me</a>
          </h1>
        </div>
      </div>
    </div>
  </div>
</header>
<img src="{% static 'blog/img/me-circle.jpg' %}" style="width:250px;height:250px;" class="center-img">
<!-- Main Content -->
<article>
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        <p>Random text describing about yourself.</p>

        <p>More random text</p>

        <p>This is a link to the <a class="blue-links" href="{% url 'blog:history' %}">blog</a></p>

        <p>This is a link to the <a class="blue-links" href="{% url 'blog:portfolio' %}">portfolio</a></p>
      </div>
    </div>
  </div>
</article>
{% endblock %}

blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

  <head>
    
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    
    <title>Tab Title</title>
    <!-- Bootstrap core CSS -->
    <link href="{% static 'blog/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Custom fonts for this template -->
    <link href="{% static 'blog/vendor/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

    <!-- Custom styles for this template -->
    <link href="{% static 'blog/css/clean-blog.min.css' %}" rel="stylesheet">
     <!-- My Custom CSS -->
    <link href="{% static 'blog/vendor/bootstrap/css/custom.css' %}" rel="stylesheet" type="text/css">
  </head>

  <body>
    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-light fixed-top " id="mainNav">
      <div class="container">
        <a class="navbar-brand" href="{% url 'blog:index' %}">Brand Name</a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          Menu
          <i class="fa fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'blog:index' %}">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'blog:about' %}">About</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'blog:history' %}">Blog</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'blog:portfolio' %}">Portfolio</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    {% block content %}
    {% endblock %}

    <!-- Footer -->
    <footer>
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-md-10 mx-auto">
            <ul class="list-inline text-center">
              <li class="list-inline-item">
                <a href="">
                  <span class="fa-stack fa-lg">
                    <i class="fa fa-circle fa-stack-2x"></i>
                    <i class="fa fa-linkedin fa-stack-1x fa-inverse"></i>
                  </span>
                </a>
              </li>
              <li class="list-inline-item">
                <a href="">
                  <span class="fa-stack fa-lg">
                    <i class="fa fa-circle fa-stack-2x"></i>
                    <i class="fa fa-github fa-stack-1x fa-inverse"></i>
                  </span>
                </a>
              </li>
            </ul>
            <p class="copyright text-muted custom-copyright">Copyright &copy; 2018 Websitename &#9679; Your Name</p>
          </div>
        </div>
      </div>
    </footer>

    <!-- Bootstrap core JavaScript -->
    <script src="{% static 'blog/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'blog/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Custom scripts for this template -->
    <script src="{% static 'blog/js/clean-blog.min.js' %}"></script>
  </body>

</html>

blog/templates/blog/detail.html
{% extends 'blog/base.html' %}
{% block content %} 
{% load static %} 
<!-- Page Header -->
<header class="masthead" style="background-image: url('{% static 'blog/img/background.jpg' %}')">
  <div class="overlay"></div>
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        <div class="post-heading">
          {% if post.pub_date %}
            <h1 class="custom-background-title word-break">{{ post.post_title }}</h1>
            <h5 class="custom-background-title">
              By Your Name on {{ post.pub_date }}
            </h5>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
</header>
<!-- Post Content -->
<article>
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        {% load martortags %}
        <p>{{ post.post_text|safe_markdown }}</p>
      </div>
    </div>
  </div>
</article>
<!--Disqus integration-->
<div class="container">
  <div class="row">
    <div class="col-lg-8 col-md-10 mx-auto">
      {% load disqus_tags %}
      {% disqus_show_comments %}
      {% set_disqus_identifier post.slug %}
      {% set_disqus_url post.get_absolute_url %}
      {% set_disqus_title post.post_title %}
    </div>
  </div>
</div>
{% endblock %}

blog/templates/blog/history.html
{% extends 'blog/base.html' %}
{% block content %}
{% load static %}
{% load taggit_templatetags2_tags %}
<!-- Page Header -->
<header class="masthead" style="background-image: url('{% static 'blog/img/background.jpg' %}')">
  <div class="overlay"></div>
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        <div class="site-heading">
          <h1>
            <a class="custom-background-title" href="{% url 'blog:history' %}">Blog Posts</a>
          </h1>
        </div>
      </div>
    </div>
  </div>
</header>
<!--category list-->
<div class="container">
  <div class="row">
    <div class="col-lg-8 col-md-10 mx-auto">
      <h1 class="custom-sub-head">
        Categories
      </h1>
      <div id="sub-head-list">
        <ul>
          {% for category_object in category %}
            {% if forloop.last %}
              <li>
                <a class="blue-links" href="{{ category_object.get_absolute_url }}">{{ category_object.category_name }}</a>
              </li>
            {% else %}
              <li>
              <a class="blue-links" href="{{ category_object.get_absolute_url }}">{{ category_object.category_name }}</a>
              <span style="color: rgb(134, 142, 150);"> &#9679; </span>
            </li>
            {% endif %}
          {% endfor %}
        </ul>
      </div>
      <hr>
    </div>
  </div>
</div>
<!--Post List -->
{% if latest_post_list %}
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        {% load martortags %}
        {% for post in latest_post_list %}
          <div class="post-preview">
            <a href="{{ post.get_absolute_url }}">
              <h2 class="post-title custom-title-list">
                {{ post.post_title }}
              </h2>
            </a>
            {% if post.pub_date %}
              <h5 class="custom-date-list">By Your Name on {{ post.pub_date }}</h5>
            {% endif %}
            <p>{{post.post_text|safe_markdown|truncatechars_html:150}}</p>
            {% if post.category %}
            <div id="post-tag-list">
              <ul>Category: 
                <li>
                  <a class="blue-links" href="{{ post.category.get_absolute_url }}">{{ post.category }}</a>
                </li>
              </ul>
            </div>
            {% endif %}
            <div id="post-tag-list">
            {% get_tags_for_object post as "tags" %}
              {% if tags.all %}
              <ul>Tags: 
                {% for tag in tags %}
                  <li><a class="blue-links" href="{% url 'blog:tagged' tag.slug %}">{{tag}}</a></li>
                {% endfor %}
              </ul>
              {% endif %}
            </div>
          </div>
          <hr>
        {% endfor %}
        <!-- Pagination -->
        {% if is_paginated %}
          {% load proper_paginate %}
          {% load link_name %}
          <ul class="pagination">
              {% if page_obj.number == 1 %}
                  <li class="disabled"><span>⇤</span></li>
              {% else %}
                  <li><a href={{ request.get_full_path|link_name:1 }}>⇤</a></li>
              {% endif %}
              {% if page_obj.has_previous %}
                  <li>&nbsp;<a href={{ request.get_full_path|link_name:page_obj.previous_page_number }}>&laquo;</a>&nbsp;</li>
              {% else %}
                  <li class="disabled">&nbsp;<span>&laquo;</span>&nbsp;</li>
              {% endif %}
              {% for i in paginator|proper_paginate:page_obj.number %}
                  {% if page_obj.number == i %}
                      <li class="active"><span><font color="red"> {{ i }} </font><span class="sr-only">(current)</span></span>&nbsp;</li>
                  {% else %}
                      <li><a href={{ request.get_full_path|link_name:i }}>{{ i }} </a>&nbsp;</li>
                  {% endif %}
              {% endfor %}
              {% if page_obj.has_next %}
                  <li>&nbsp;<a href={{ request.get_full_path|link_name:page_obj.next_page_number }}>&raquo;</a>&nbsp;</li>
              {% else %}
                  <li class="disabled">&nbsp;<span>&raquo;</span>&nbsp;</li>
              {% endif %}
              {% if page_obj.number == paginator.num_pages %}
                  <li class="disabled"><span>⇥</span></li>
              {% else %}
                  <li><a href={{ request.get_full_path|link_name:paginator.num_pages }}>⇥</a></li>
              {% endif %}
          </ul>
        {% endif %}
      </div>
    </div>
  </div>
{% else %}
  <p>No posts are available</p>
{% endif %}
{% endblock %}

blog/templates/blog/index.html
{% extends 'blog/base.html' %}
{% block content %}
{% load static %}
{% load taggit_templatetags2_tags %}
<!-- Page Header -->
<header class="masthead" style="background-image: url('{% static 'blog/img/background.jpg' %}')">
  <div class="overlay"></div>
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        <div class="site-heading">
          <h1>
            <a class="custom-background-title" href="{% url 'blog:index' %}">Your Name</a>
            <span class="subheading">A witty subheading</span>
          </h1>
        </div>
      </div>
    </div>
  </div>
</header>
<!--Post List -->
{% if latest_post_list %}
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        <h1 class="custom-sub-head">Recent Posts</h1>
        <hr>
        {% load martortags %}
        {% for post in latest_post_list %}
          <div class="post-preview">
            <a href="{{ post.get_absolute_url }}">
              <h2 class="post-title custom-title-list">
                {{ post.post_title }}
              </h2>
            </a>
            {% if post.pub_date %}
              <h5 class="custom-date-list">By Your Name on {{ post.pub_date }}</h5>
            {% endif %}
            <p>{{post.post_text|safe_markdown|truncatechars_html:150}}</p>
            {% if post.category %}
            <div id="post-tag-list">
              <ul>Category: 
                <li>
                  <a class="blue-links" href="{{ post.category.get_absolute_url }}">{{ post.category }}</a>
                </li>
              </ul>
            </div>
            {% endif %}
            <div id="post-tag-list">
            {% get_tags_for_object post as "tags" %}
              <ul>Tags: 
                {% for tag in tags %}
                  <li><a class="blue-links" href="{% url 'blog:tagged' tag.slug %}">{{tag}}</a></li>
                {% endfor %}
              </ul>
            </div>
          </div>
          <hr>
        {% endfor %}
        <!-- Pager -->
        <div class="clearfix">
          <a class="btn btn-primary float-right custom-older-posts" href="{% url 'blog:history' %}">All Posts &raquo;</a>
        </div>
      </div>
    </div>
  </div>
{% else %}
  <p>No posts are available</p>
{% endif %}
{% endblock %}

blog/templates/blog/portfolio.html
{% extends 'blog/base.html' %}
{% block content %} 
{% load static %} 
<!-- Page Header -->
<header class="masthead" style="background-image: url('{% static 'blog/img/background.jpg' %}')">
  <div class="overlay"></div>
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        <div class="site-heading">
          <h1>
            <a class="custom-background-title" href="{% url 'blog:portfolio' %}">Portfolio</a>
          </h1>
        </div>
      </div>
    </div>
  </div>
</header>

<!-- Main Content -->
<article>
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        <!-- Education -->
        <h1 class="custom-calibri">
          <u>Education</u>
        </h1>
        <h3 class="custom-calibri">
          <a class="blue-links" href=""> Your School Name </a>
        </h3>
        <h5 class="custom-calibri">
          <a class="blue-links">Bachelor of Science in Computer Science</a>
          <span style="color: rgb(134, 142, 150);"> &#9679; </span>
          <font color="#868E96">August 2014 – May 2018</font>
        </h5>
        <br>
        <!-- Work Experience -->
        <h1 class="custom-calibri">
          <u>Work Experience</u>
        </h1>
        <h3 class="custom-calibri"><a class="blue-links" href="">Software Research Intern</a></h3>
        <h5 class="custom-calibri">Your School Name
          <span style="color: rgb(134, 142, 150);"> &#9679; </span>
          <font color="#868E96">June 2014 – August 2014</font>
        </h5>
        <p class="custom-calibri">
          Describe your job duties here.
        </p>
        <!-- Projects -->
        <h1 class="custom-calibri">
          <u>Projects</u>
        </h1>
        <h3 class="custom-calibri">
          <a class="blue-links" href="">Personal Website</a>
        </h3>
        <h5 class="custom-calibri">
          <a class="blue-links">Developer, Writer, Administrator</a>
          <span style="color: rgb(134, 142, 150);"> &#9679; </span>
          <font color="#868E96">June 2018 – Present</font>
        </h5>
        <p class="custom-calibri">
          Describe your project here.
        </p>
        <!-- Technical Skills -->
        <h1 class="custom-calibri">
          <u>Technical Skills</u>
        </h1>
        <h3 class="custom-calibri">Languages:</h3>
        <div style="float: left; width: 50%;">
          <ul class="custom-calibri">
            <li>Python</li>
            <li>CSS</li>
            <li>C++</li>
            <li>MATLAB</li>
          </ul>
        </div>
        <div style="float: right; width: 50%;">
          <ul class="custom-calibri">
            <li>Java</li>
            <li>HTML</li>
            <li>MIPS</li>
            <li>R</li>
          </ul>
        </div>
        <h3 class="custom-calibri">Operating Systems:</h3>
        <div>
          <ul class="custom-calibri">
            <li>macOS</li>
            <li>Linux</li>
            <li>Windows</li>
          </ul>
        </div>
        <h3 class="custom-calibri">Tools, Frameworks, Libraries:</h3>
        <div style="float: left; width: 50%;">
          <ul class="custom-calibri">
            <li>Amazon Web Services</li>
            <li>Bash Scripting</li>
            <li>GNU Make</li>
            <li>JDBC</li>
            <li>Visio</li>
          </ul>
        </div>
        <div style="float: right; width: 50%;">
          <ul class="custom-calibri">
            <li>Django</li>
            <li>Git</li>
            <li>Java Message Service</li>
            <li>Bootstrap</li>
            <li>Sublime Text</li>
          </ul>
        </div>
        <h3 class="custom-calibri">Databases:</h3>
        <div>
          <ul class="custom-calibri">
            <li>PostgreSQL</li>
            <li>SQLite</li>
            <li>MySQL</li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</article>
{% endblock %}